services:
  mongo:
    image: mongo
    container_name: ${DB_HOST}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}

    ports:
      - ${DB_PORT}:27017
    volumes:
      - /data/db
    networks:
      - arena-network
    
      
    
  node:
    build: .
    container_name: arena
    restart: always
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mongo
    # environment:
    #   - VIRTUAL_HOST=arena.lafuentedanel.com
    #   - LETSENCRYPT_HOST=arena.lafuentedanel.com
    #   - LETSENCRYPT_EMAIL=admin@lafuentedanel.com
    expose:
      - "3000"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - arena-network
      # - nginx-proxy

networks:
  arena-network:
    name: arena-network
  # nginx-proxy:
  #   external: true
    
